version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./model.pkl:/app/model.pkl
      - ./healthcare_dataset.csv:/app/healthcare_dataset.csv
    environment:
      - MODEL_PATH=/app/model.pkl
      - PYTHONUNBUFFERED=1 # Ensures logs are streamed immediately
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 3

